name: 'Build oereb-db-structure'
on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        env:
          CONTAINERNAME: database
        run: |
          docker build -t oereb-db-structure:intermediate .
          docker run --name $CONTAINERNAME -d -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} -e POSTGRES_DB=${{ secrets.POSTGRES_DB }} -e POSTGRES_HOST_AUTH_METHOD=md5 -e PG_READ_PWD=${{ secrets.PG_READ_PWD }} -e PG_WRITE_PWD=${{ secrets.PG_WRITE_PWD }} -e PG_GRETL_PWD=${{ secrets.PG_GRETL_PWD }} oereb-db-structure:intermediate
          until docker exec $CONTAINERNAME pg_isready; do
            echo "$CONTAINERNAME was not ready, waiting another cycle"
            sleep 5
          done
          docker exec $CONTAINERNAME rm -f /docker-entrypoint-initdb.d/20_setup.sql
          docker exec $CONTAINERNAME rm -f /docker-entrypoint-initdb.d/30_initdb_user.sh
          echo "$CONTAINERNAME is ready..."
          docker commit $CONTAINERNAME ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:latest
